name: YesYesYes

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Build and Test
        working-directory: .
        run: |-
          npm i
          npm test
          npm run build

  publish-gpr:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: Release.txt
          name: "${{ steps.package-version.outputs.current-version}}"
          tag_name: "${{ steps.package-version.outputs.current-version}}"

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm i
      - run: npm run build
      - run: npm run release
      - run: npm ci
#      - run: npm dist-tag add @mrfreemind/analytics-producer@1.0.17 3iugoiqw23
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
